### PR TITLE
added fdescribe method and made describe.only call describe 

### PR DESCRIPTION
**Pull request by faceyspacey**
i wonder what it would take to make the `only` methods actually work??

### CODE REVIEW

**Comment by mthuret** [comment]
Hi @faceyspacey, what would you expect as an output of the `only` inside the specs panel? 

Right now is just a way to not break if this function is used within a test runner. But it could possible to add an information to indicate the "only" test that can be displayed. I don't know if that make sense however.

**Comment by faceyspacey** [comment]
it could all be made to work exactly as you would expect. It just takes some hackery. I got some bigger somewhat related challenges I'm trying to solve first. The hacking may not be necessary if we can get some changes in Storybook.  

Have you had a chance to check out what I've been working on yet?

I think I linked you this before:
https://github.com/faceyspacey/animated-transition-group

it's been majorly upgraded. It now uses a facade package I made to provide both facades as seamlessly as possible: 

https://github.com/faceyspacey/jest-storybook-facade

The biggest challenge I'm working to fix is that Storybook doesn't let you provide your own `<Provider>` without a decorator in a way that works with HMR. Everything I'm doing is with Redux in mind--I could care less about a toy component viewer which becomes unmaintainable as the real app diverges over time; I need the real app in Storybooy, which means Redux. So the second concern is the ability for the `add` handler's to be async, i.e.:

``
.add('with text', async () => {
    const store = configureStore()
    await store.dispatch(someAsyncActionCreator())

   return createApp(store)
})
```

They are ultimately minor issues, but I have a feeling I may have to make customizations the storybook team doesn't care for, in which case I'm totally fine forking it. I think storybook is a fantastic concept, and a lot more can be done with it. Specifically the unified testing interface shown in my above links--a concept you initially pioneered! 

So I'm going to research making the 2 fixes i mentioned (Redux Provider HMR + Async stories) and get familiar with the underlying Storybook code. Then depending on how deep I must get, we can circle back and determine how to handle minor things like `describe.only`. For now your initial strategy is totally fine. That feature is primarily for a real test runner anyway. If I end up having to hack the internals of storybook it will make it a lot easier to solve that anyway. 

Either way check out `animated-transition-group`. Run the tests, run the storybook. You will notice the stories in Storybook have a few console errors, but that doesn't prevent storybook from working. In fact if you change the sub-story in storybook the errors don't show, and HMR works on the component code--just not the test code. It's no big deal, but it needs to be on point to become something widely used.

**Comment by mthuret** [comment]
That's interesting, basically you generate the stories based on the test right? 

Hopefully I'll be able to work on the Specs V2 soon. I'll will keep in mind what you did :)

**Comment by faceyspacey** [comment]
yea, tests that return a story element. That way your tests don't have to change. 

The premise is this: serious projects will be apprehensive to make use of the current specifications addon interface. Those tests won't be what they rely on in their CI environment, etc. They are too afraid to break their standard structure for tests. For tests paired with storybook to become extremely popular, storybook has to work with existing tests. Plus, just imagine being able to add one line of code per test (the `return`) and having Storybook work. This interface has a lot of potential for popularity. 

I got more of it to work with HMR. Basically the only issue remaining is being able to return promises from `add`, just as you can use promises and `async/await` with your normal `it` tests in Jest.

**Pull request merged**
