### PR TITLE
Cumulative Build Updates, Boilerplate Reduction

### PR DESCRIPTION
**Pull request by darthtrevino**
This PR includes everything from the other PRs. I did some testing in the storybook instance of this project to make sure that the test runner worked in the browser as well as the CLI. I had only tested an `npm link`ed project in my other branches.

Here's what I changed:
- create common mocking implementation
- action() mock returns a function, which is what storybook returns.
- npm build scripts, update .gitignore and .npmignore
- Add missing dev dependencies
- Reduce required boilerplate to get up and running
- Expose `describe`, `it`, etc.. as window globals to match the CLI execution environment

### CODE REVIEW

**Comment by mthuret** [comment]
Hi there,

I didn't have time to look after you pull request, but I see you just closed it. Any particular reason for that ?

**Comment by darthtrevino** [comment]
Hey! Sorry, I got busy working on other things. I closed the PR because I thought maybe it was too large in scope, I'd be glad to reopen it though.

**Comment by mthuret** [comment]
Great, I take a look probably this week-end, and give you a feedback :)

**Comment by SpaceK33z** [comment]
I really like the idea of reducing the boilerplate. Having to use `specs(() => describe('...', function() {})` feels a bit counter-intuitive. Only having to use `describe` is much better.

Also "hiding" the exact webpack config is nice. This will make it easier to change some things in this package without everyone having to update their webpack config.

**Comment by mthuret** [comment]
Actually my bad, I didn't take the time to look after this huge PR.

About removing the specs() function, I agree that can simplify a lot!
However I'm not sure about hiding all the boilerplate under webpack. @darthtrevino is it something easily overridable? While working on it, those files can change a lot depending on your needs or what you wants to achieve. 

In order for me to be able to move forward on it, do you think it's possible to split the PR between different functional topics?

**Comment by darthtrevino** [comment]
Sure, I can put together a few PRs

**Comment by ndelangen** [comment]
@darthtrevino Thank you for your work! Would it be possible for you to do a few smaller PR's? This PR is too hard to process in one go. I hope you understand.

**Pull request closed without merging**
